apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sftp-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sftp-server.name" . }}
    helm.sh/chart: {{ include "sftp-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sftp-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sftp-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      containers:
        - name: sftp-server
          image: "quay.io/openvnf/sftp:alpine-3.7"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          volumeMounts:
            - name: sftp-config
              mountPath: /etc/sftp/
            - name: data
              mountPath: /home/sftp/
            - name: authorized-keys
              mountPath: /home/sftp/.ssh/keys/
            # - name: ssh-host-keys
            #   mountPath: /etc/ssh/ssh_host_rsa_key
            #  subPath: ssh_host_rsa_key
          livenessProbe:
            tcpSocket:
              port: 22
          readinessProbe:
            tcpSocket:
              port: 22
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
      - name: sftp-config
        configMap:
          name: {{ include "sftp-server.fullname" . }}-users
      #- name: authorized-keys
      #  configMap:
      #    name: {{ template "sftp-server.fullname" . }}-authorized-keys
      #- name: ssh-host-keys
      #  secret:
      #    secretName: {{ .Values.sftpConfig.hostKeys.secret }}
      #    defaultMode: 384
      - name: data
        persistentVolumeClaim:
          size: 5Mi
          #claimName: {{ template "sftp-server.fullname" . }}-data
